services:
  rdtclient:
    image: rogerfar/rdtclient:${RDTCLIENT_TAG}
    restart: unless-stopped
    expose:
      - "6500"
    networks:
      - edge
    env_file:
      - /apartmentlab/gitops/env/${ENV}/rdtclient.env
    volumes:
      - /apartmentlab/data/${ENV}/rdtclient/data:/data/db
      - /apartmentlab/data/${ENV}/rdtclient/data:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:6500 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s

  rdtclient_pub:
    image: alpine/socat
    restart: unless-stopped
    profiles: ["preprod"]
    networks:
      - edge
    ports:
      - "6501:6500"
    command: tcp-listen:6500,fork,reuseaddr tcp-connect:prowlarr:6500
    depends_on:
      - rdtclient

networks:
  edge:
    external: true
