services:
  rdtclient:
    image: rogerfar/rdtclient
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - <path to data>:/data/db
      - <path to downloads>:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:9696/api/v1/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s

  prowlarr_pub:
    image: alpine/socat
    restart: unless-stopped
    profiles: ["preprod"]
    networks:
      - edge
    ports:
      - "9697:9696"
    command: tcp-listen:9696,fork,reuseaddr tcp-connect:prowlarr:9696
    depends_on:
      - prowlarr

networks:
  edge:
    external: true
